### ISSUE TITLE
UnicodeDecodeError when running the reporter

### ISSUE THREAD

**Issue by santiagomalter** [codeclimate/python-test-reporter#20] opened 2016-04-23 15:48 UTC
Thanks for releasing a Python reporter!

I tried to run the reporter locally, got the following error.

Note that I have the same error in my build environment. (CodeShip)

My [.coverage file](http://pastebin.com/wc7tDqtA).

Hope it helps, do not hesitate if you need any other information.

# Packages version
```
coverage==4.0.3
django-coverage-plugin==1.2
codeclimate-test-reporter==0.1.0
```

# Environment
```
(env)smalter-retina:expert-adventure smalter$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
```

# .coveragerc
```
[run]
include = sl/*
omit =
  *migrations*
  *commands*
  *autofixtures*
  *tests.py*
  

plugins = django_coverage_plugin
```
# Traceback
```bash
(env)smalter-retina:expert-adventure smalter$ coverage run manage.py test -k
(env)smalter-retina:expert-adventure smalter$ CODECLIMATE_REPO_TOKEN=XYZ codeclimate-test-reporter
Traceback (most recent call last):
  File "/Users/smalter/Repositories/expert-adventure/env/bin/codeclimate-test-reporter", line 11, in <module>
    sys.exit(run())
  File "/Users/smalter/Repositories/expert-adventure/env/lib/python2.7/site-packages/codeclimate_test_reporter/__main__.py", line 11, in run
    sys.exit(runner.run())
  File "/Users/smalter/Repositories/expert-adventure/env/lib/python2.7/site-packages/codeclimate_test_reporter/components/runner.py", line 49, in run
    exit_status = reporter.run()
  File "/Users/smalter/Repositories/expert-adventure/env/lib/python2.7/site-packages/codeclimate_test_reporter/components/reporter.py", line 36, in run
    payload = formatter.payload()
  File "/Users/smalter/Repositories/expert-adventure/env/lib/python2.7/site-packages/codeclimate_test_reporter/components/formatter.py", line 19, in payload
    source_files = self.__source_files()
  File "/Users/smalter/Repositories/expert-adventure/env/lib/python2.7/site-packages/codeclimate_test_reporter/components/formatter.py", line 54, in __source_files
    payload = file_coverage.payload()
  File "/Users/smalter/Repositories/expert-adventure/env/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 13, in payload
    "blob_id": self.__blob(),
  File "/Users/smalter/Repositories/expert-adventure/env/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 42, in __blob
    return sha1((header + contents).encode("utf-8")).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2986: ordinal not in range(128)
```

**Comment by dblandin** [comment] 2016-04-26 14:33
Hey @santiagomalter,

Thanks for the detailed issue! Looks like we're not handling ascii encoded files well.

Would you be willing to provide a reproducible test case? If you're able to reproduce the issue with a test project, zipping up the files and attaching the archive to this issue would be very helpful. You can run `codeclimate-test-reporter --stdout` to run the reporter without communicating with codeclimate.com. Alternatively, you can add @codeclimate-support as a collaborator to your project.

I'll try to reproduce the issue locally, but having that test case available would be useful.

Thanks!

**Comment by lzaslav** [comment] 2016-05-04 20:18
I'm getting same error when source files have byte order mark.

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 10: ordinal not in range(128) codeclimate-test-reporter returned exit code 1`

**Comment by santiagomalter** [comment] 2016-05-05 09:24
Hey @lzaslav, did you managed to solve the issue on your side?

**Comment by lzaslav** [comment] 2016-05-05 14:15
@santiagomalter, I ended up removing BOM from my source files but that's just a workaround.

**Comment by morgan** [comment] 2016-05-06 08:21
Same issue here: `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 26698: ordinal not in range(128)`

**Comment by dblandin** [comment] 2016-05-09 20:03
Hey everyone + @albertyw,

I've just released a new version of our python test reporter, `v0.1.1`, which has a fix for this decoding issue. Please try it out and let me know if it works for you.

Thanks!

**Comment by santiagomalter** [comment] 2016-05-10 10:11
Thanks! I'll check :)

**Comment by santiagomalter** [comment] 2016-05-10 10:25
One word: 👌 

Thanks for the reactivity.

**Comment by dblandin** [comment] 2016-05-10 13:35
Awesome! :tada:

Thanks again for the report!

**Closed by dblandin** 2016-05-10 13:35 UTC

**Comment by morgan** [comment] 2016-06-12 06:28
@dblandin I'm still seeing this:

```
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.3/bin/codeclimate-test-reporter", line 9, in <module>
    load_entry_point('codeclimate-test-reporter==0.1.1', 'console_scripts', 'codeclimate-test-reporter')()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/__main__.py", line 11, in run
    sys.exit(runner.run())
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/components/runner.py", line 49, in run
    exit_status = reporter.run()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/components/reporter.py", line 36, in run
    payload = formatter.payload()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/components/formatter.py", line 19, in payload
    source_files = self.__source_files()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/components/formatter.py", line 54, in __source_files
    payload = file_coverage.payload()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 18, in payload
    "blob_id": self.__blob(),
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 44, in __blob
    contents = self.__file_body()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 51, in __file_body
    self.file_body = open(self.__filename(), "r", encoding="utf-8-sig").read()
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/home/ubuntu/virtualenvs/venv-2.7.3/lib/python2.7/encodings/utf_8_sig.py", line 66, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 1313: invalid continuation byte
```

**Comment by dblandin** [comment] 2016-06-14 18:16
Hi @morgan,

I think your last comment might warrant a new issue. The error is certainly similar but I wonder if it's a different encoding issue:

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 1313: invalid continuation byte
```

vs

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2986: ordinal not in range(128)
```

Also, if you're able, a reproducible test case would help us nail down a fix quicker. Thanks!

**Comment by DEKHTIARJonathan** [comment] 2016-06-29 15:22
Hi @dblandin,

I have some trouble too. The following error is generated while building in Travis.

```
$ codeclimate-test-reporter --stdout
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/codeclimate-test-reporter", line 9, in <module>
    load_entry_point('codeclimate-test-reporter==0.1.2', 'console_scripts', 'codeclimate-test-reporter')()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/__main__.py", line 11, in run
    sys.exit(runner.run())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/components/runner.py", line 49, in run
    exit_status = reporter.run()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/components/reporter.py", line 36, in run
    payload = formatter.payload()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/components/formatter.py", line 19, in payload
    source_files = self.__source_files()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/components/formatter.py", line 54, in __source_files
    payload = file_coverage.payload()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 18, in payload
    "blob_id": self.__blob(),
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 44, in __blob
    contents = self.__file_body()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 51, in __file_body
    self.file_body = open(self.__filename(), "r", encoding="utf-8-sig").read()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/encodings/utf_8_sig.py", line 66, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 23423: invalid start byte
```

Any clue how to fix this ?
